### ISSUE TITLE
FluentFilteredExtension on File: No gridfield is shown in CMS

### ISSUE THREAD

**Issue by sanderha** [tractorcow-farm/silverstripe-fluent#500]
I've applied the `FluentFilteredExtension` to `File` like this:
```
SilverStripe\Assets\File:
  extensions:
    - TractorCow\Fluent\Extension\FluentFilteredExtension
```
And I can see the correct DB tables are created, aswell as it working in the frontend. In CMS however, no gridfield is added to the File editform.
Maybe this is because the extension is trying to add a "Root" tab which is not present on `File`?

Just thought I'd create this issue

**Comment by robbieaverill** [comment]
Thanks for raising this. The file CMS edit form is a React form, and there is currently no support for GridFields in React which is why you're not seeing anything pop up. There's not anything Fluent can do other than not use a GridField, so I think I'll close this in favour of https://github.com/silverstripe/silverstripe-admin/issues/463

**Comment by sanderha** [comment]
I see.
I added the locales with a `ListBoxField` instead, which worked "ok"

**Comment by robbieaverill** [comment]
Ok great - thanks for providing a workaround 👍
