### ISSUE TITLE
Wrong record is being deleted from _Localised table

### ISSUE THREAD

**Issue by baukezwaan** [tractorcow-farm/silverstripe-fluent#570]
We are experiencing an issue with the handling of deletes in the latest version(s) of Fluent. When the latest record of for instance a Page is deleted, the deteleBaseRecord is being called. 
This function deletes the record from several tables, and does this based on ID. This goes wrong for the _Localised table. There the selection should be on RecordID instead.

How to reproduce:
- fresh install of SS4 + Fluent ^4 (tested on 4.4.1 and 4.4.3)
- create some Locales
- add some pages, and save them in multiple languages (to make the ID higher than the RecordID in the version table) 
- Now; add a new page via the CMS
- Remember the ID (for instance id=16)
- Check which record is in SiteTree_Localised on ID=16
- Delete the page via the CMS
- See record ID=16 is gone in SiteTree_Localised (instead of RecordID=16)

The snippet below fixes the issue, but probably not in the most elegant way... 🤕 

```
    protected function deleteBaseRecord(DataObject $record)
    {

        //... (collapsed)

        foreach ($queriedTables as $table) {
            
            if (strpos(strtolower($table), '_localised') > 0 ) {
                $delete = SQLDelete::create("\"{$table}\"", array('"RecordID"' => $record->ID));
            } else {
                $delete = SQLDelete::create("\"{$table}\"", array('"ID"' => $record->ID));
            }
```

**Comment by robbieaverill** [comment]
Perhaps the issue is that the policy is running on records it shouldn't? I think `DeleteLocalisationPolicy` is supposed to delete localised records, whereas `DeleteRecordPolicy` is supposed to delete the main record (but not localisations)

**Comment by tractorcow** [comment]
Darn, you are right! I see the error now thanks for spotting that :)

**Comment by tractorcow** [comment]
The only change I'd make to your fix is that deleteBaseRecord() should never delete _localised records at all.

**Comment by tractorcow** [comment]
Safer option:

```php
    protected function deleteBaseRecord(DataObject $record)
    {
        $queriedTables = FluentState::singleton()
            ->withState(
                function (FluentState $state) use ($record) {
                    // Disable fluent and delete unlocalised record only
                    $state->setLocale(null);

                    // Copy DataObject::delete() here for now
                    $srcQuery = DataList::create(get_class($record))
                        ->filter('ID', $record->ID)
                        ->dataQuery()
                        ->query();

                    return $srcQuery->queriedTables();
                }
            );

        foreach ($queriedTables as $table) {
            $delete = SQLDelete::create("\"{$table}\"", array('"ID"' => $record->ID));
            $delete->execute();
        }
    }
```

**Comment by tractorcow** [comment]
Fix at https://github.com/tractorcow-farm/silverstripe-fluent/pull/573

**Comment by baukezwaan** [comment]
Thanks for looking into this! Just to get my understanding right, would this solution leave the _Localised records in the table as orphans? Or should these be cleaned earlier in the chain (by DeleteLocalisationPolicy)?

**Comment by baukezwaan** [comment]
To answer my own question: yes, the DeleteLocalisationPolicy already takes care of this.
Thanks a lot for the fix!

**Comment by tractorcow** [comment]
Well, it's not working properly yet... the issue still exists. :) I'll leave this ticket open until we can merge the fix and tag it.

This is a really important fix and we need to get anyone on an old version upgraded ASAP.

**Comment by blueskies79** [comment]
Bauke, thanks so much for finding the source of this bug! And Tractorcow, thanks for fixing it so quickly! 

Just leaving a comment here for those who might be running into this issue and just seeing the effects of it. We had about 2-3 months of crazy trouble with this fluent issue, since we had an importer running on our site that deleted old records (so regular batch deletes) and added new ones. So this bug was triggered regularly. 

Our observations:
- Every now and then a page in a local would suddenly be unpublished. The page that becomes unpublished is totally random, there can be a delay between any trigger and the unpublish (depending on your project's caching setup).
- If editors published a page in a locale, sometimes the Title would change to Untitled and not be publishable. The page that turns Untitled removes the MenuTitle as well and causes an endless-loop-error when trying to open the page in the CMS.

So if you're experiencing the above issues --> upgrade. Then realize that your database is now broken and has orphaned _Live records without a draft version (which were incorrectly deleted). This will continue to cause issues until those records have both a draft and live version again.

Again: the above is just to catch some Google searchers that might be running into the weird side effects of this bug. ;-)
