### ISSUE TITLE
Question: Is it "ok" to use Locale codes that are language only (no region)?

### ISSUE THREAD

**Issue by chrispenny** [tractorcow-farm/silverstripe-fluent#611]
Hi team,

A project I'm on is needing to free up all of it's `en_..` Locales (as it wants to use them), but is also still needing a general "international English" Locale.

I've been playing around with using just `en` as the code to represent this Locale, and while everything appears to be working fine, I was just hoping to check that there isn't anything obvious that I've missed (or if there are plans to specifically **not** support this paradigm in the future).

`Locale::getLocaleSuffix()` is the only (minor) exception that I've found, but this is easy enough to work around.

Thank you for your time!

**Comment by tractorcow** [comment]
Since we are internally setting a language code for localisation, you'll need to assign a specific locale (not simply language) to the default region. Since `en` is not enough to do things like specify regional date formatting logic.

I would just create a locale with url segment "en", call it "English" and then pick an english locale that most closely approximates the locale I want to use. Unless you look at the page source you won't see the underlying locale :)

**Comment by chrispenny** [comment]
Thanks, @tractorcow 

> I would just create a locale with url segment "en", call it "English" and then pick an english locale that most closely approximates the locale I want to use.

This is actually what we did originally. The issue is that they now want to start creating localisations for that particular Locale - so we're now in the position of needing to "move" the international code to another.

The date formatting logic you mentioned, is that SS core, or Fluent?

Generally speaking I'm still keen to try and figure out how I can add support for languages without region - otherwise I risk having to go through this "rename" process for Int every time they determine that they need a new localisation that's in English.

**Comment by tomaszpirc** [comment]
@chrispenny On our project we wanted to use at first a locale for International English. There are two locales `en_001` (English World) or `en_150` (English Europe), but they were not available. So we ended up using locale for en_IE (English Ireland) since it is the most suitable for use as International English on EU based projects. It has a date format ddMMYYYY and uses € for currency.  So, I agree with @tractorcow that in the end you will have to decide which locale to use for International English. At least until `en_001` and `en_150` become widely available. 

A nice article about this topic https://www.ctrl.blog/entry/en-001.html

**Comment by chrispenny** [comment]
Thank you, @tomaszpirc. I appreciate the follow up.

**Comment by tractorcow** [comment]
> The date formatting logic you mentioned, is that SS core, or Fluent?

SS Core as well as PHP core. All of the php-intl code requires the locale be set to a valid locale code, and silverstripe's i18n is the same.

At the lowest level, if you can get the server to support the locale via ICU then you should be able to use it in PHP. https://www.php.net/manual/en/intl.requirements.php

This is partly why, if you recall, SilverStripe had to drop the old `lc_XX` (lolcat locale) because it wasn't system supported anywhere.

**Comment by chrispenny** [comment]
Thanks, @tractorcow! That's really useful context.

**Comment by chrispenny** [comment]
Just to add a comment for anyone else that might stumble in here. We've decided to adopt the territory code of `001` ("World"), which seems to be much more widely supported as a concept. Thanks again to Tomasz for mentioning that one.

http://site.icu-project.org/design/t/territory-region-apis
http://unicode.org/reports/tr35/#Unicode_Language_and_Locale_Identifiers

>  The territory code ‘001’ (the World) is used to indicate a standardized form, such as “ar-001” for Modern Standard Arabic.

**Comment by tractorcow** [comment]
Sounds good to me :)

**Comment by tomaszpirc** [comment]
@chrispenny Glad I could help. @tractorcow Maybe it would be useful though if this two options (for World/Europe English) are available in Silverstripe Locale module in the dropdown by default. What do you think?

**Comment by tractorcow** [comment]
I think I could add a guide to the fluent module on how to add these, but probably not a part of silvestripe core. It's definitely worth knowing how to add this though.
