### ISSUE TITLE
Question: Create localase many to many

### ISSUE THREAD

**Issue by Agon2299** [tractorcow-farm/silverstripe-fluent#762]
@tractorcow Hi. I don't find solution to my problem. How I can localize relationships 'many to many' ? Thanks!

**Comment by tractorcow** [comment]
hi @Agon2299 , you can create a has_many through via a localised dataobject, and then apply fluentextension to that object. By localising the parent_id and child_id fields on that relation, you will have in effect a localised many many.

**Comment by bummzack** [comment]
@tractorcow Just a quick question regarding this setup… I have a `many_many through` relation and applied `Versioned`, as well as `FluentVersionedExtension` to the "glue" DataObject.
Interestingly, I always see all linked records (files in this case) in the CMS (in all locales). I can remove one record in one locale, but it'll show up again.

Records seem to show up correctly in the frontend though. Any pointers how to resolve this? It would be nice if the CMS Editors would see the same records that are being shown in the frontend.

Or would you suggest to just use a regular `many_many` relation with locale filtering instead?

**Comment by tractorcow** [comment]
Well, one thing you could try is:
 - remove Versioned (it'll cause problems)
 - remove FluentVersionedExtension
 - apply FluentIsolatedExtension
 - remove "translate" config (not needed with isolated extension).

Now you'll have a separate pivot record for each locale. You will need to create the relationship for each locale individually though, but you might find that easier and less buggy than trying to use a localisd relationship.

The difference between the two approaches is that now we add a `Locale` column directly to the pivot, and filter based on that, instead of joining the parent / child id columns in a _Localised table.
